services:
  backend:
    build:
      context: ./backend
    ports:
      - "7331:7331"
  frontend:
    build:
      context: ./frontend
    ports:
      - "4321:4321"
    depends_on:
      - backend
